apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: playeconomy-host
spec:
  hostname: playeconomy.eastus.cloudapp.azure.com
  acmeProvider:
    email: ijevtic459@gmail.com
  tlsSecret:
    name: playeconomy-tls